import { Button, VerticalBox, LineEdit, CheckBox, Palette, HorizontalBox, TextEdit } from "std-widgets.slint";

export component AppWindow inherits Window {
	title: "HTTP Toolkit Patcher";
	icon: @image-url("./assets/icon.svg");
	width: 400px;
	height: 400px;
	default-font-size: 16px;
	in-out property <string> asar_path: "Could not detect Asar file";
	in property <string> patcher_version: "0.0.0";
	in property <string> log: "";
	in property <bool> can_patch: true;
	callback select_asar_path();
	callback patch_asar_file();

	VerticalBox {
		alignment: start;
		spacing: 10px;
		padding: 15px;


		Text {
			text: "HTTP Toolkit Patcher";
			font-size: 32px;
			horizontal-alignment: center;
		}

		Text {
			text: "Select an Asar file to patch";
			font-size: 20px;
			horizontal-alignment: center;
			color: Palette.foreground.transparentize(40%);
		}

		Rectangle { height: 10px; }

		Button {
			text: "Select Asar file";
			clicked => root.select_asar_path();
		}

		Text {
			text: asar_path;
			color: Palette.foreground.transparentize(30%);
			horizontal-alignment: center;
			wrap: word-wrap;
			font-size: 14px;
		}

		Rectangle {}

		Button {
			enabled: can_patch;
			text: "Patch";
			clicked => root.patch_asar_file();
		}


		Rectangle {
			background: Palette.background.transparentize(50%);
			height: 33%;
			width: 100%;
			log_view := TextEdit {
				font-size: 14px;
				read-only: true;
				placeholder-text: "Press the 'Patch' button to get started";
				text: log;
				width: 100%;
				height: 100%;
			}
		}

		 Timer {
			interval: 100ms;
			running: true;
			triggered() => {
				log_view.viewport-y = min(0px, - log_view.viewport-height + log_view.visible-height);
			}
		}

	}
	VerticalBox {
		y: 15px;
		x: 15px;
		alignment: end;
		HorizontalBox {
			alignment: end;

			Text {
				font-size: 13px;
				text: "v" + patcher_version;
			}
		}
	}
}
